# Generated by Django 4.2.6 on 2023-10-27 11:20

import accounts.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
        ('accounts', '0003_serviceproviderprofile_farmerprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='agriculturalexpertprofile',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farm_location',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farm_size',
        ),
        migrations.AddField(
            model_name='agriculturalexpertprofile',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalexpertprofile',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.farm'),
        ),
        migrations.AlterField(
            model_name='agriculturalexpertprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='store_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
