# Generated by Django 4.2.6 on 2023-10-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='area',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='county',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
