# Generated by Django 4.2.6 on 2023-11-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_useraccount_area_remove_useraccount_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_profile_images/'),
        ),
    ]
