# Generated by Django 4.2.6 on 2023-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_farmerprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturalexpertprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='expert_profile_images/'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='provider_profile_images/'),
        ),
    ]
