# Generated by Django 4.2.6 on 2023-10-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='produce',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
