# Generated by Django 4.2.6 on 2023-10-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_produce_content_type_produce_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='produce',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='produce',
        ),
    ]
