# Generated by Django 4.2.6 on 2023-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_remove_crop_farm_remove_crop_produce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
