# Generated by Django 4.2.6 on 2023-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_crop_number_livestock_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
