# Generated by Django 4.2.6 on 2023-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_alter_crop_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livestock_images/'),
        ),
    ]
