# Generated by Django 4.2.6 on 2023-10-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_tool_store_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tools_images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Needs Maintenance', 'Needs Maintenance')], default='Good', max_length=20),
        ),
    ]
