# Generated by Django 4.2.6 on 2023-10-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_tool_image_alter_tool_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tools_images/'),
        ),
    ]
