# Generated by Django 4.2.6 on 2023-10-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_alter_tool_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='last_maintenance_date',
            field=models.DateField(null=True),
        ),
    ]
