# Generated by Django 4.2.6 on 2023-10-29 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_alter_tool_last_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.store'),
        ),
    ]
