# Generated by Django 4.2.6 on 2023-10-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_tool_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Needs Maintenance', 'Needs Maintenance'), ('Out For Maintenace', 'Out For Maintenace')], default='Good', max_length=20),
        ),
    ]
