# Generated by Django 4.2.6 on 2023-10-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_alter_tool_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Needs Maintenance', 'Needs Maintenance'), ('Under Maintenance', 'Under Maintenance')], default='Good', max_length=20),
        ),
    ]
