# Generated by Django 4.2.6 on 2023-11-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_alter_tool_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmactivity',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
