# Generated by Django 4.2.6 on 2023-11-03 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_useraccount_area_remove_useraccount_county_and_more'),
        ('farm', '0014_farmactivity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to='accounts.serviceproviderprofile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
