# Generated by Django 4.2.6 on 2023-11-05 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0015_service_service_provider_alter_service_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
