# Generated by Django 4.2.6 on 2023-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_alter_service_availability_status_alter_service_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('Planting', 'Planting'), ('Ploughing', 'Ploughing'), ('Weeding', 'Weeding')], max_length=20, null=True),
        ),
    ]
