# Generated by Django 4.2.6 on 2023-11-07 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0019_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmactivity',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmactivity',
            name='resources_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
